# Lang
language: zh-CN

# Header
menu:
  主页: /
  归档: /archives
  分类: /category
  标签: /tag
#  关于: /about
# 订阅: /atom.xml

# Content
fancybox: false

#Copyright
copyright: false

#EOF line
eof: "END"

# Table Of Contents
toc:
  enable: true

# Miscellaneous
google_analytics:
favicon: /favicon.ico
twitter:
google_plus:
fb_admins:
fb_app_id:


# Profile
nickname: Winter`s Notes
description: Live Happy Love Hard
blog_name: NoteBook
blog_url: /archives
links:
  NoteBook: /archives


# Info
archive_footer_content: "<div class='end-of-file'>Live Happy Love Hard</div>"
post_footer_content: "<div class='end-of-file'>Live Happy Love Hard</div>"
