language: node_js

node_js:
 - 10.15.3

notifications:
  email:
    on_success: never
    on_failure: change
install:
  - npm install

srcript: 


after_script:
  - hexo g
  - gulp
  - ls
  - cd ./public
  - git init 
  - git config user.name "summerandwinter"
  - git config user.email "ly1989124423@163.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

branches:
  only:
    - master
env:
 global:
   - GH_REF: github.com/summerandwinter/summerandwinter.github.io.git