# Lang
language: zh-CN

# Header
menu:
  主页: /
  归档: /archives
  分类: /category
  标签: /tag
#  关于: /about
# 订阅: /atom.xml

# Content
fancybox: false

#Copyright
copyright: false

#EOF line
eof: "END"

# Table Of Contents
toc:
  enable: true

# Miscellaneous
google_analytics:
favicon: /favicon.ico
twitter:
google_plus:
fb_admins:
fb_app_id:


# Profile
nickname: Winter`s Notes
description: Live Happy Love Hard
blog_name: NoteBook
blog_url: /archives
links:
  NoteBook: /archives


# Info
archive_footer_content: "<div class='end-of-file'>Live Happy Love Hard</div>"
post_footer_content: "<div class='end-of-file'>Live Happy Love Hard</div>"

# Gitment
gitment:
  enable: true
  owner: summerandwinter
  repo: summerandwinter.github.io
  client:
    id: 7b432b7b46e71966fd88
    secret: 2c697bec7b012bca975de41c87863d84086f8d81

# Utterances
# NOTICE) make sure the app is installed on the repo before using this commit system
# see https://utteranc.es/ for more
utterances:
  enable: false
  repo: summerandwinter/summerandwinter.github.io # your repo in this format: 'username/reponame', note that there is no '.git' suffix    


# If you want to use valine,you should get the appId and appKey form https://leancloud.cn ,more setting please see https://valine.js.org
valine:
  enable: false # !!if you want use valine comment system,please set enable: true
  appId:  Gb3NgQmIATbymMeFxECohqkY-gzGzoHsz #your leancloud appId
  appKey:  OkpJkJDove69qiYuw85GoWCP #your leancloud appKey
  guest_info: nick,mail,link #valine comment header info
  placeholder: Just go go # valine comment input placeholder(like: Please leave your footprints )
  avatar: mm # gravatar style https://valine.js.org/avatar
  pageSize: 10 # comment list page size
  verify: false # valine verify code (true/false)
  notify: false # valine mail notify (true/false)
  lang: zh-cn
 
# Donate
donate:
  enable: true
  github: https://github.com/summerandwinter
  paypal: https://www.paypal.me/
  bitcoin: 1234567890
  BTCQR: /images/donate/bitcoin.jpg
  AliPayQR: /images/donate/alipayQR.jpg
  WeChatQR: /images/donate/wechatQR.jpg 